// Fit-score strings (professional side): factor names, the "Why this score?" explainer and receipt, result cards, the
// jargon tooltips and the score components / flags generated by lib/search.ts. Client-safe. See ../pro.ts for the
// glossary; band labels and meanings come from LABELS[lang].bands, impact tiers from LABELS[lang].impact.
import { fmtNum, fmtPct, joinList, plural, type Lang } from "../pro";

type Basis = "condition" | "area" | "all" | "none";
type LogKey = "indication" | "phase" | "area" | "recent" | "pediatric";

// ---------- English ----------

const n_ = (n: number) => fmtNum(Math.round(n), "en");
const tr = (n: number) => plural(Math.round(n), "trial", undefined, "en");
const s_ = (n: number) => (n === 1 ? "" : "s");

const en = {
  /** Plain-language explanations for jargon, shown in small "?" tooltips. */
  glossary: {
    fitScore:
      "How well this hospital matches your trial, from 0 to 100. Based on its registered trials in your condition and phase, recent activity, finished trials and size, compared with other Madrid hospitals.",
    accredited:
      "A research institute officially accredited by Spain's Carlos III Health Institute (ISCIII). It means an established team and setup for clinical research.",
    similarNow:
      "Trials for the same condition currently recruiting at this hospital. Patients get shared between trials, so many similar trials can slow your recruitment.",
    newToTrials:
      "We found no trials for this hospital in the public registries, so we can't score its experience. It may still have the capacity, and the questionnaire asks.",
  },

  /** Plain-English name and one-line meaning per factor (the receipt and the methodology page). */
  factors: {
    indication: {
      name: "Experience in your condition",
      plain: "How many trials this hospital has run in your condition, compared with the most experienced Madrid hospital for this search.",
      why: "Teams that have recruited these patients before know where to find them and how to screen them.",
    },
    phase: {
      name: "Experience in your phase",
      plain:
        "Trials in the same phase as yours (for example Phase II) in your condition. Only when no Madrid hospital has trials in your condition does it count the therapeutic area instead.",
      why: "Early-phase and late-phase trials need different set-ups: units, monitoring and patient numbers.",
    },
    area: {
      name: "Therapeutic-area depth",
      plain: "Trials across the wider therapeutic area (for example all of oncology), not just your exact condition.",
      why: "A deep department has the specialists, nurses and pharmacy routines your trial will rely on.",
    },
    recent: {
      name: "Recent activity",
      plain: "Trials started this calendar year or in the 3 years before it, counted on the same trials as phase experience.",
      why: "Shows the team is running trials now, not just in the past.",
    },
    completion: {
      name: "Completion track record",
      plain: "Share of finished trials in the area that completed rather than being terminated or withdrawn.",
      why: "Hospitals whose trials usually finish are less likely to leave you short of patients.",
    },
    capacity: {
      name: "Hospital capacity",
      plain: "Size of the hospital in beds, from the national hospital catalogue (800 beds or more = full points).",
      why: "Bigger hospitals see more patients and usually have more research staff.",
    },
    pediatric: {
      name: "Paediatric experience",
      plain: "Relevant trials that enrolled children.",
      why: "Paediatric trials need child-specific consent, dosing and facilities.",
    },
  } as Record<string, { name: string; plain: string; why: string }>,

  deductions: {
    competing: {
      name: "Competition",
      plain:
        "Similar trials recruiting at this hospital right now could compete for the same patients. Up to −10, by their share of the hospital's trials in your condition.",
    },
    equipment: {
      name: "Equipment not in the catalogue",
      plain:
        "Required equipment you selected that the national hospital catalogue does not list for this hospital: −5 per item, up to −10. It may still be there, so confirm with the site.",
    },
  },

  /** Generated explanation phrases (score-explain.ts). `b` is a basis suffix from `basis`, `ph` a phase label for
   *  running text, `since` the first year counted as recent. */
  explain: {
    basis: { condition: " in your condition", area: " in the therapeutic area", all: " (any condition)", none: "" } as Record<Basis, string>,
    mostInMadrid: (top: number) => `Most in Madrid: ${n_(top)}`,
    theMost: "The most of any Madrid hospital",
    /** "the most of any Madrid hospital" / "2nd most in Madrid" / "top 5 in Madrid" (largest: hospital size). */
    rank: (rank: number, largest: boolean): string | null => {
      const most = largest ? "largest" : "most";
      if (rank === 1) return `the ${most} of any Madrid hospital`;
      const o = ["th", "st", "nd", "rd"];
      if (rank <= 3) return `${rank}${o[rank] ?? o[0]} ${most} in Madrid`;
      if (rank <= 5) return "top 5 in Madrid";
      if (rank <= 10) return "top 10 in Madrid";
      return null;
    },
    inCondition: (n: number) => `${tr(n)} in your condition`,
    phaseTrials: (n: number, ph: string, b: string) => `${plural(Math.round(n), `${ph} trial`, undefined, "en")}${b}`,
    inArea: (n: number) => `${tr(n)} in the area`,
    inTherapeuticArea: (n: number) => `${tr(n)} in the therapeutic area`,
    overall: (n: number) => `${plural(Math.round(n), "registered trial", undefined, "en")} overall`,
    recent: (n: number, b: string, since: number) => `${tr(n)}${b} started in ${since} or later`,
    pediatric: (n: number, b: string) => `${tr(n)}${b} enrolling children`,
    tooFew: "Too few finished trials to judge",
    halfPoints: "Neutral: half points",
    completionOf: (rate: number, n: number) => `${fmtPct(rate, "en")} of ${plural(Math.round(n), "finished trial", undefined, "en")} completed`,
    completion: (rate: number) => `${fmtPct(rate, "en")} of finished trials completed`,
    beds: (n: number) => `${n_(n)} beds`,
    bedsFull: (over: boolean): string => (over ? "800+ beds = full points" : "800 beds = full points"),
    // holding it back
    tag: (p: number, max: number) => ` (${p} of ${max} pts)`,
    competingHold: (n: number, pen: number) => `${plural(n, "similar trial", undefined, "en")} recruiting here now (−${pen})`,
    equipmentHold: (items: string[], pen: number) => `${items.join(", ")} not listed in the national catalogue (−${pen})`,
    noCondition: "No registered trials in your exact condition",
    vsTop: (n: number, top: number) => `${tr(n)} in your condition, vs ${n_(top)} at the most experienced hospital`,
    phaseHold: (n: number, ph: string, b: string) => `${n === 0 ? "No" : n_(n)} ${ph} trial${s_(n)}${b}`,
    recentHold: (n: number, b: string, since: number) => `${n === 0 ? "No trials" : tr(n)}${b} started in ${since} or later`,
    tooFewCompletion: "Too few finished trials to judge completion",
    smaller: (n: number) => `Smaller hospital: ${n_(n)} beds`,
    // what would raise it
    raise: (key: LogKey, gain: number, k: number, ph: string, b: string, areaChosen: boolean, since: number) => {
      const what =
        key === "indication"
          ? `registered trial${s_(k)} in your condition`
          : key === "phase"
            ? `${ph} trial${s_(k)}${b}`
            : key === "area"
              ? areaChosen
                ? `trial${s_(k)} in the therapeutic area`
                : `registered trial${s_(k)} overall`
              : key === "recent"
                ? `trial${s_(k)}${b} started in ${since} or later`
                : `trial${s_(k)}${b} enrolling children`;
      return `+${gain} with ${n_(k)} more ${what}`;
    },
    raiseCompletion: (lost: number, rate: number) => `Up to +${lost} with a stronger completion record (now ${fmtPct(rate, "en")})`,
    raiseCompeting: (pen: number, n: number) => `+${pen} back as the ${plural(n, "similar recruiting trial", undefined, "en")} close`,
    raiseEquipment: (pen: number, items: string[]) => `+${pen} if ${items.join(" and ")} were listed in the catalogue, or once the site confirms it`,
    siteKnowledge: "Your own knowledge of the site may change this picture.",
    relativeCaveat: "Full points = the most experienced Madrid hospital for this search.",
  },

  /** Score line, stacked bar, reasons and the "Why this score?" receipt (ScoreExplain.tsx). */
  receipt: {
    rank: (rank: number) => `#${rank}`,
    of: "of",
    forSearch: "for this search",
    stackAria: (score: number, parts: string, penalty: number) => `Fit score ${score} of 100: ${parts}${penalty ? `; minus ${penalty} for deductions` : ""}`,
    pointsOf: (name: string, p: number, max: number) => `${name} ${p} of ${max}`,
    deductionsTitle: (pen: number) => `Deductions: −${pen}`,
    strengthSr: "Strength: ",
    holdingSr: "Holding it back: ",
    madridMedian: "Madrid median",
    top: "top",
    largest: "largest",
    topHospital: "Top hospital",
    caption: "Why this score: points per factor, deductions and total",
    factor: "Factor",
    impact: "Impact",
    thisHospital: "This hospital",
    points: "Points",
    baseScore: "Base score",
    deductions: "Deductions",
    fitScore: "Fit score",
    floor: "The score can't go below 0",
    competingFact: (n: number) => `${plural(n, "similar trial", undefined, "en")} recruiting here now`,
    equipmentFact: (items: string[]) => `${items.join(", ")} not listed`,
    nothingMissing: "Nothing missing",
    competingSub: "Up to −10, by share of its trials in your condition",
    equipmentSub: "−5 per item, up to −10 · may still be there: we ask",
    equipmentNone: "All required equipment is listed (or none required)",
    barLabel: (name: string, p: number, max: number) => `${name}: ${p} of ${max} points`,
    relative: "Experience points compare Madrid hospitals with each other for this search.",
    howLink: "How scoring works →",
    raiseTitle: "What would raise this score?",
  },

  /** Result cards (ResultCard.tsx). */
  card: {
    beds: (n: number) => `${n_(n)} beds`,
    bedsNote: "Installed beds as reported in the national hospital catalogue (data as of 31 Dec 2024).",
    bedsNoteShort: "Installed beds as reported in the national hospital catalogue.",
    public: "Public",
    private: "Private",
    inCondition: "In your condition",
    inConditionLong: "Trials in your condition",
    phaseTrials: (ph: string) => `${ph} trials`,
    similar: "Similar recruiting",
    similarLong: "Similar trials recruiting now",
    whatIs: (term: string) => `What is “${term}”?`,
    statTitle: (n: number, long: string) => `${n_(n)} ${long.charAt(0).toLowerCase()}${long.slice(1)}`,
    why: "Why this score?",
    whyRegion: (name: string, score: number) => `Why ${name} scores ${score}`,
    how: "How scoring works",
    sources: "Sources",
    sourcesTitle: "Where these numbers come from",
    sourcesNote: "Trial counts come from the public registries (deduplicated); beds and equipment from the national hospital catalogue.",
    onMap: "On map",
    details: "Details",
    equipTitle: "Equipment not listed in the national catalogue",
    equipNote: "The catalogue lists major equipment only. A hospital may still have access, e.g. through a partner site. The questionnaire asks.",
    equipNoteShort: "The catalogue lists major equipment only; the questionnaire asks the hospital.",
    /** After the list of missing items; `count` picks the Spanish verb form. */
    equipMissing: (() => ": not listed in the national hospital catalogue, so we'll ask the hospital") as (count: number) => string,
    shortlisted: "Shortlisted",
    shortlist: "Shortlist",
    accredited: (inst: string) => `Accredited institute · ${inst}`,
    accreditedWhat: "What is an accredited research institute?",
    newToTrials: "New to registered trials, so no score yet",
    whyNoScore: "Why is there no score?",
    chips: {
      indication: "Trials in your condition",
      indicationNote: (q: string) => `Registered trials matching “${q}”, counted once across REec and ClinicalTrials.gov.`,
      phase: "Trials in your phase",
      phaseNote: "Trials in your phase and your condition (the therapeutic area only when no Madrid hospital has trials in your condition).",
      area: "Trials in the therapeutic area",
      overall: "Registered trials overall",
      recent: "Recent trials",
      recentNote: (since: number) => `Relevant trials that started in ${since} or later.`,
      finished: "Finished trials",
      finishedNote: "Finished trials in the area: completed, terminated or withdrawn.",
      pediatric: "Trials enrolling children",
      competing: "Similar trials recruiting now",
      competingNote: "Trials in your condition recruiting at this hospital now, per the registries.",
    },
  },

  /** Score components and flags generated by lib/search.ts. */
  engine: {
    label: {
      indication: "Indication experience",
      phase: (ph: string) => `${ph} experience`,
      area: "Therapeutic area depth",
      recent: "Recent activity",
      completion: "Completion track record",
      capacity: "Hospital capacity",
      pediatric: "Paediatric experience",
    },
    scope: { condition: "this condition", area: "the therapeutic area", all: "all registered trials" } as Record<Exclude<Basis, "none">, string>,
    indication: (n: number, q: string) => `${n_(n)} registered trial${s_(n)} matching "${q}"`,
    phase: (n: number, ph: string, scope: string) => `${n_(n)} ${ph} trial${s_(n)} in ${scope}`,
    area: (n: number) => `${n_(n)} trial${s_(n)} in the therapeutic area`,
    overall: (n: number) => `${n_(n)} registered trial${s_(n)} overall`,
    recent: (n: number, scope: string, since: number) => `${n_(n)} trial${s_(n)} in ${scope} started in ${since} or later`,
    completionNone: "Not enough finished trials to judge (neutral)",
    completion: (rate: number, n: number) => `${Math.round(rate * 100)}% of ${n_(n)} finished trial${s_(n)} completed`,
    beds: (n: number) => `${n_(n)} beds`,
    pediatric: (n: number, scope: string) => `${n_(n)} trial${s_(n)} in ${scope} enrolling children`,
    flagCompeting: (n: number) => `${n_(n)} similar trial${s_(n)} recruiting now for this condition`,
    flagEquipment: (items: string[]) => `${items.join(", ")}: not listed in the national hospital catalogue, so we'll ask the hospital`,
    flagNoIndication: "No registered trials in this exact condition yet",
    flagNoPediatric: "No paediatric trial history found",
    flagNoResearchUnit: "No research institute on file. Confirm the contact route.",
  },
};

// ---------- Spanish ----------

const nE = (n: number) => fmtNum(Math.round(n), "es");
const ens = (n: number) => plural(Math.round(n), "ensayo", "ensayos", "es");
/** "iniciado" / "iniciados" (agrees with ensayo/s). */
const ini = (n: number) => (n === 1 ? "iniciado" : "iniciados");
const lista = (items: string[]) => joinList(items, "es");
/** "no figura" / "no figuran" for one or several items. */
const figura = (items: string[]) => (items.length === 1 ? "figura" : "figuran");

const es: typeof en = {
  glossary: {
    fitScore:
      "Indica, de 0 a 100, cuánto encaja este hospital con tu ensayo. Se basa en sus ensayos registrados en tu indicación y fase, su actividad reciente, sus ensayos finalizados y su tamaño, comparados con los de otros hospitales de Madrid.",
    accredited:
      "Instituto de investigación sanitaria acreditado por el Instituto de Salud Carlos III (ISCIII). Supone un equipo y una estructura consolidados para la investigación clínica.",
    similarNow:
      "Ensayos de la misma indicación que están reclutando ahora en este hospital. Los pacientes se reparten entre ensayos, así que muchos ensayos similares pueden frenar tu reclutamiento.",
    newToTrials:
      "No hemos encontrado ensayos de este hospital en los registros públicos, así que no podemos puntuar su experiencia. Puede que aun así tenga capacidad: el cuestionario lo pregunta.",
  },

  factors: {
    indication: {
      name: "Experiencia en tu indicación",
      plain: "Cuántos ensayos ha realizado este hospital en tu indicación, comparado con el hospital de Madrid con más experiencia para esta búsqueda.",
      why: "Los equipos que ya han reclutado a estos pacientes saben dónde encontrarlos y cómo hacer el cribado.",
    },
    phase: {
      name: "Experiencia en tu fase",
      plain:
        "Ensayos de la misma fase que el tuyo (por ejemplo, fase II) en tu indicación. Solo cuando ningún hospital de Madrid tiene ensayos en tu indicación se cuenta, en su lugar, el área terapéutica.",
      why: "Los ensayos de fases tempranas y tardías necesitan estructuras distintas: unidades, monitorización y número de pacientes.",
    },
    area: {
      name: "Profundidad en el área terapéutica",
      plain: "Ensayos en el conjunto del área terapéutica (por ejemplo, toda la oncología), no solo en tu indicación exacta.",
      why: "Un servicio con trayectoria cuenta con los especialistas, la enfermería y la rutina de farmacia en los que se apoyará tu ensayo.",
    },
    recent: {
      name: "Actividad reciente",
      plain: "Ensayos iniciados este año natural o en los 3 anteriores, contados sobre los mismos ensayos que la experiencia en la fase.",
      why: "Muestra que el equipo está haciendo ensayos ahora, no solo en el pasado.",
    },
    completion: {
      name: "Historial de finalización",
      plain: "Proporción de ensayos finalizados del área que se completaron, en lugar de interrumpirse o retirarse.",
      why: "Los hospitales cuyos ensayos suelen llegar a término tienen menos riesgo de dejarte sin pacientes.",
    },
    capacity: {
      name: "Capacidad del hospital",
      plain: "Tamaño del hospital en camas, según el Catálogo Nacional de Hospitales (800 camas o más = puntuación máxima).",
      why: "Los hospitales grandes atienden a más pacientes y suelen tener más personal de investigación.",
    },
    pediatric: {
      name: "Experiencia pediátrica",
      plain: "Ensayos relevantes que incluyeron niños.",
      why: "Los ensayos pediátricos requieren consentimiento, dosificación e instalaciones específicos para niños.",
    },
  },

  deductions: {
    competing: {
      name: "Competencia",
      plain:
        "Los ensayos similares que están reclutando ahora en este hospital pueden competir por los mismos pacientes. Hasta −10, según su peso entre los ensayos del hospital en tu indicación.",
    },
    equipment: {
      name: "Equipamiento fuera del catálogo",
      plain:
        "Equipamiento necesario que has seleccionado y que el Catálogo Nacional de Hospitales no recoge para este hospital: −5 por elemento, hasta −10. Puede que sí lo tenga: confírmalo con el centro.",
    },
  },

  explain: {
    basis: { condition: " en tu indicación", area: " en el área terapéutica", all: " (cualquier indicación)", none: "" },
    mostInMadrid: (top: number) => `Máximo en Madrid: ${nE(top)}`,
    theMost: "El primero de Madrid",
    rank: (rank: number, largest: boolean): string | null => {
      if (rank === 1) return largest ? "el más grande de Madrid" : "el primero de Madrid";
      if (rank <= 3) return largest ? `el ${rank}.º más grande de Madrid` : `el ${rank}.º de Madrid`;
      if (rank <= 5) return "entre los 5 primeros de Madrid";
      if (rank <= 10) return "entre los 10 primeros de Madrid";
      return null;
    },
    inCondition: (n: number) => `${ens(n)} en tu indicación`,
    phaseTrials: (n: number, ph: string, b: string) => `${ens(n)} de ${ph}${b}`,
    inArea: (n: number) => `${ens(n)} en el área`,
    inTherapeuticArea: (n: number) => `${ens(n)} en el área terapéutica`,
    overall: (n: number) => `${ens(n)} ${n === 1 ? "registrado" : "registrados"} en total`,
    recent: (n: number, b: string, since: number) => `${ens(n)}${b} ${ini(n)} en ${since} o después`,
    pediatric: (n: number, b: string) => `${ens(n)}${b} ${n === 1 ? "que incluye" : "que incluyen"} niños`,
    tooFew: "No hay suficientes ensayos finalizados para valorarlo",
    halfPoints: "Neutral: la mitad de los puntos",
    completionOf: (rate: number, n: number) => `${ens(n)} ${n === 1 ? "finalizado" : "finalizados"}: se completó el ${fmtPct(rate, "es")}`,
    completion: (rate: number) => `Se completó el ${fmtPct(rate, "es")} de los ensayos finalizados`,
    beds: (n: number) => `${nE(n)} camas`,
    bedsFull: (over: boolean) => (over ? "800 camas o más = puntuación máxima" : "800 camas = puntuación máxima"),
    tag: (p: number, max: number) => ` (${p} de ${max} pts)`,
    competingHold: (n: number, pen: number) =>
      `${n === 1 ? "1 ensayo similar" : `${nE(n)} ensayos similares`} en reclutamiento ahora en este hospital (−${pen})`,
    equipmentHold: (items: string[], pen: number) => `${lista(items)}: no ${figura(items)} en el Catálogo Nacional de Hospitales (−${pen})`,
    noCondition: "Ningún ensayo registrado en tu indicación exacta",
    vsTop: (n: number, top: number) => `${ens(n)} en tu indicación, frente a ${nE(top)} en el hospital con más experiencia`,
    phaseHold: (n: number, ph: string, b: string) => `${n === 0 ? "Ningún ensayo" : ens(n)} de ${ph}${b}`,
    recentHold: (n: number, b: string, since: number) => `${n === 0 ? "Ningún ensayo" : ens(n)}${b} ${ini(n === 0 ? 1 : n)} en ${since} o después`,
    tooFewCompletion: "No hay suficientes ensayos finalizados para valorar la finalización",
    smaller: (n: number) => `Hospital más pequeño: ${nE(n)} camas`,
    raise: (key: LogKey, gain: number, k: number, ph: string, b: string, areaChosen: boolean, since: number) => {
      const one = k === 1;
      const n = one ? "1 ensayo" : `${nE(k)} ensayos`;
      const what =
        key === "indication"
          ? `${n} ${one ? "registrado" : "registrados"} más en tu indicación`
          : key === "phase"
            ? `${n} de ${ph} más${b}`
            : key === "area"
              ? areaChosen
                ? `${n} más en el área terapéutica`
                : `${n} ${one ? "registrado" : "registrados"} más en total`
              : key === "recent"
                ? `${n} más${b} ${ini(k)} en ${since} o después`
                : `${n} más${b} ${one ? "que incluya" : "que incluyan"} niños`;
      return `+${gain} con ${what}`;
    },
    raiseCompletion: (lost: number, rate: number) => `Hasta +${lost} con un mejor historial de finalización (ahora, ${fmtPct(rate, "es")})`,
    raiseCompeting: (pen: number, n: number) =>
      n === 1 ? `+${pen} cuando se cierre el ensayo similar en reclutamiento` : `+${pen} a medida que se cierren los ${nE(n)} ensayos similares en reclutamiento`,
    raiseEquipment: (pen: number, items: string[]) => `+${pen} si ${lista(items)} ${figura(items) === "figura" ? "figurara" : "figuraran"} en el catálogo, o cuando el centro lo confirme`,
    siteKnowledge: "Lo que tú sepas del centro puede cambiar esta valoración.",
    relativeCaveat: "Puntuación máxima = el hospital de Madrid con más experiencia para esta búsqueda.",
  },

  receipt: {
    rank: (rank: number) => `${rank}.º`,
    of: "de",
    forSearch: "en esta búsqueda",
    stackAria: (score: number, parts: string, penalty: number) =>
      `Puntuación de idoneidad ${score} de 100: ${parts}${penalty ? `; menos ${penalty} por deducciones` : ""}`,
    pointsOf: (name: string, p: number, max: number) => `${name} ${p} de ${max}`,
    deductionsTitle: (pen: number) => `Deducciones: −${pen}`,
    strengthSr: "Punto fuerte: ",
    holdingSr: "Lo que más resta: ",
    madridMedian: "Mediana de Madrid",
    top: "máximo",
    largest: "el mayor",
    topHospital: "Hospital líder",
    caption: "Por qué esta puntuación: puntos por factor, deducciones y total",
    factor: "Factor",
    impact: "Impacto",
    thisHospital: "Este hospital",
    points: "Puntos",
    baseScore: "Puntuación base",
    deductions: "Deducciones",
    fitScore: "Puntuación de idoneidad",
    floor: "La puntuación no baja de 0",
    competingFact: (n: number) => `${n === 1 ? "1 ensayo similar" : `${nE(n)} ensayos similares`} en reclutamiento ahora en este hospital`,
    equipmentFact: (items: string[]) => `${lista(items)}: no ${figura(items)} en el catálogo`,
    nothingMissing: "No falta nada",
    competingSub: "Hasta −10, según su peso entre sus ensayos en tu indicación",
    equipmentSub: "−5 por elemento, hasta −10 · puede que sí lo tenga: lo preguntamos",
    equipmentNone: "Figura todo el equipamiento necesario (o no se exige ninguno)",
    barLabel: (name: string, p: number, max: number) => `${name}: ${p} de ${max} puntos`,
    relative: "Los puntos de experiencia comparan entre sí los hospitales de Madrid para esta búsqueda.",
    howLink: "Cómo puntuamos →",
    raiseTitle: "¿Qué subiría la puntuación?",
  },

  card: {
    beds: (n: number) => `${nE(n)} camas`,
    bedsNote: "Camas instaladas según el Catálogo Nacional de Hospitales (datos a 31 de diciembre de 2024).",
    bedsNoteShort: "Camas instaladas según el Catálogo Nacional de Hospitales.",
    public: "Público",
    private: "Privado",
    inCondition: "En tu indicación",
    inConditionLong: "Ensayos en tu indicación",
    phaseTrials: (ph: string) => `Ensayos de ${ph.replace(/^Fase/, "fase")}`,
    similar: "Similares en reclutamiento",
    similarLong: "Ensayos similares en reclutamiento",
    whatIs: (term: string) => `¿Qué significa «${term}»?`,
    statTitle: (n: number, long: string) => `${nE(n)} · ${long}`,
    why: "¿Por qué esta puntuación?",
    whyRegion: (name: string, score: number) => `Por qué ${name} tiene ${score} puntos`,
    how: "Cómo puntuamos",
    sources: "Fuentes",
    sourcesTitle: "De dónde salen estas cifras",
    sourcesNote:
      "Los recuentos de ensayos proceden de los registros públicos (sin duplicados); las camas y el equipamiento, del Catálogo Nacional de Hospitales.",
    onMap: "En el mapa",
    details: "Detalles",
    equipTitle: "Equipamiento que no figura en el catálogo nacional",
    equipNote:
      "El catálogo solo recoge el equipamiento de alta tecnología. El hospital puede tener acceso igualmente, por ejemplo a través de otro centro: el cuestionario lo pregunta.",
    equipNoteShort: "El catálogo solo recoge el equipamiento de alta tecnología; el cuestionario se lo pregunta al hospital.",
    equipMissing: (count: number) => `: no ${count === 1 ? "figura" : "figuran"} en el Catálogo Nacional de Hospitales; se lo preguntaremos al hospital`,
    shortlisted: "Preseleccionado",
    shortlist: "Preseleccionar",
    accredited: (inst: string) => `Instituto acreditado · ${inst}`,
    accreditedWhat: "¿Qué es un instituto de investigación acreditado?",
    newToTrials: "Sin ensayos registrados: no hay puntuación",
    whyNoScore: "¿Por qué no tiene puntuación?",
    chips: {
      indication: "Ensayos en tu indicación",
      indicationNote: (q: string) => `Ensayos registrados que coinciden con «${q}», contados una sola vez entre REec y ClinicalTrials.gov.`,
      phase: "Ensayos en tu fase",
      phaseNote: "Ensayos en tu fase y tu indicación (el área terapéutica solo cuando ningún hospital de Madrid tiene ensayos en tu indicación).",
      area: "Ensayos en el área terapéutica",
      overall: "Ensayos registrados en total",
      recent: "Ensayos recientes",
      recentNote: (since: number) => `Ensayos relevantes iniciados en ${since} o después.`,
      finished: "Ensayos finalizados",
      finishedNote: "Ensayos finalizados del área: completados, interrumpidos o retirados.",
      pediatric: "Ensayos que incluyen niños",
      competing: "Ensayos similares en reclutamiento",
      competingNote: "Ensayos en tu indicación que están reclutando ahora en este hospital, según los registros.",
    },
  },

  engine: {
    label: {
      indication: "Experiencia en la indicación",
      phase: (ph: string) => `Experiencia en ${ph}`,
      area: "Profundidad en el área terapéutica",
      recent: "Actividad reciente",
      completion: "Historial de finalización",
      capacity: "Capacidad del hospital",
      pediatric: "Experiencia pediátrica",
    },
    scope: { condition: "esta indicación", area: "el área terapéutica", all: "el total de ensayos registrados" },
    indication: (n: number, q: string) => `${ens(n)} ${n === 1 ? "registrado que coincide" : "registrados que coinciden"} con «${q}»`,
    phase: (n: number, ph: string, scope: string) => `${ens(n)} de ${ph} en ${scope}`,
    area: (n: number) => `${ens(n)} en el área terapéutica`,
    overall: (n: number) => `${ens(n)} ${n === 1 ? "registrado" : "registrados"} en total`,
    recent: (n: number, scope: string, since: number) => `${ens(n)} en ${scope} ${ini(n)} en ${since} o después`,
    completionNone: "No hay suficientes ensayos finalizados para valorarlo (neutral)",
    completion: (rate: number, n: number) => `Se completó el ${fmtPct(rate, "es")} de ${ens(n)} ${n === 1 ? "finalizado" : "finalizados"}`,
    beds: (n: number) => `${nE(n)} camas`,
    pediatric: (n: number, scope: string) => `${ens(n)} en ${scope} ${n === 1 ? "que incluye" : "que incluyen"} niños`,
    flagCompeting: (n: number) => `${n === 1 ? "1 ensayo similar" : `${nE(n)} ensayos similares`} en reclutamiento ahora para esta indicación`,
    flagEquipment: (items: string[]) => `${lista(items)}: no ${figura(items)} en el Catálogo Nacional de Hospitales; se lo preguntaremos al hospital`,
    flagNoIndication: "Aún no hay ensayos registrados en esta indicación exacta",
    flagNoPediatric: "Sin historial de ensayos pediátricos",
    flagNoResearchUnit: "Sin instituto de investigación registrado: hay que confirmar la vía de contacto",
  },
};

export const SCORING: Record<Lang, typeof en> = { en, es };
export type ScoringDict = typeof en;
